miejsca = ['Norwegia','Hiszpania','Rosja','Grecja','Wlochy']
print(miejsca)
print(sorted(miejsca))
print(miejsca)
print(sorted(miejsca, reverse=True))
print(miejsca)
miejsca.reverse()
print(miejsca)
miejsca.reverse()
print(miejsca)
miejsca.sort()
print(miejsca)
miejsca.sort(reverse=True)
print(miejsca)